Add gcc-11 support (#3708)
* Use std::vector::back() to ensure filename terminates with NUL

Fix -Werror=stringop-overflow compilation error on g++-11.

* Initialize real_start_y at declaration

Fix the following error when compiling with g++-11:
  error: ‘real_start_y’ may be used uninitialized
  [-Werror=maybe-uninitialized]

* Add support for gcc-11

For grpc we had to add std=c++14 flag to make it compile because
std::string_view included in abseil was not defined due to the fact that
the CMakeLists.txt of grpc explicitly set std=c++11.
Moreover we choose std=c++14 as this what gcc-10 uses by default.